# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Also save the resulting binary as an "artifact".
# How do I download an action artifact from GitHub?
# * On GitHub, navigate to the main page of the repository.
# * Under your repository name, click Actions.
# * In the left sidebar, click the workflow you want to see.
# * From the list of workflow runs, click the name of the run you want to see.
# * Under Artifacts, click the artifact you want to download.
#
# Geht zwar, artifacts kann aber nicht jeder runterladen,
# ist also kein release ersatz.

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '17', '19' ]
    name: Java ${{ matrix.Java }} CI

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'

    - name: Cache Maven packages
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -Djavac.target=`echo "${{ matrix.java }}" | sed -e "s/-ea//g"`
