# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# Also save the resulting binary as an "artifact".
# How do I download an action artifact from GitHub?
# * On GitHub, navigate to the main page of the repository.
# * Under your repository name, click Actions.
# * In the left sidebar, click the workflow you want to see.
# * From the list of workflow runs, click the name of the run you want to see.
# * Under Artifacts, click the artifact you want to download.
#
# Geht zwar, artifacts kann aber nicht jeder runterladen,
# ist also kein release ersatz.

name: Java CI with Maven

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: binary release (.zip)
        path: |
          LICENSE
          target/awtbitmap.jar
        retention-days: 3