# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  
  schedule:
    - cron: '33 14 * * 1'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read  # for pmd/pmd-github-action to determine modified files
      pull-requests: read  # for pmd/pmd-github-action to query PRs
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up JDK 11
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@d9c1f3c5940cbf5923f1354e83fa858b4496ebaa
        with:
          analyzeModifiedFilesOnly: 'false'
          rulesets: 'quickstart.xml'
          sourcePath: 'src/main/java'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@294a9d92911152fe08befb9ec03e240add280cb3 # v3.26.8
        with:
          sarif_file: pmd-report.sarif
