# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# When a tag is pushed then also create a release,
# see https://github.com/softprops/action-gh-release

name: Create release

on:
  push:
    tags: "awtbitmap*"

env:
  JAVA_VERSION: 17
  JAVA_TARGET: 8

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-latest
    name: Release

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'zulu'

    - name: Cache Maven packages
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -Djavac.target=${{ env.JAVA_TARGET }}

    - name: Create zipfile
      run: zip -j ${{ github.ref_name }}-jar.zip LICENSE target/awtbitmap.jar

    - name: Create release and upload files
      uses: softprops/action-gh-release@d99959edae48b5ffffd7b00da66dcdb0a33a52ee # v2.0.2
      with:
        prerelease: true
        files: |
          ${{ github.ref_name }}-jar.zip
